# Generated by Django 4.2.25 on 2025-11-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0002_mensagemcontato_alter_funcionarios_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contato', models.CharField(blank=True, max_length=18, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='')),
                ('nome', models.CharField(max_length=80)),
                ('categoria', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.FloatField(max_length=20)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
